### ISSUE TITLE
Error: Can't resolve 'moment'

### ISSUE THREAD

**Issue by flamencoflsh** [samueldelesque/react-simple-charts#2]
@samueldelesque 
Hi!  I installed using the "npm install --save react-simple-charts" command, 
and added "import {Area, CirclePie, BarMetric} from 'react-simple-charts'"  

When running, I would get the error "ERROR in ./~/react-simple-charts/dist/react-simple-charts/react-simple-charts.js
Module not found: Error: Can't resolve 'moment' in '.../node_modules/react-simple-charts/dist/react-simple-charts'
 @ ./~/react-simple-charts/dist/react-simple-charts/react-simple-charts.js 1:17593-17610

Do you know what this is about?  And how it can be fixed?

Thanks!

**Comment by samueldelesque** [comment]
Hi @flamencoflsh - sorry this library is deprecated but has been ported into https://salad-ui.com/

You can try to use `npm i --save salad-ui.chart` and then `import {Area} from 'salad-ui.chart'`

**Comment by flamencoflsh** [comment]
Hi @samueldelesque !

I tried what you suggested, but still getting an error:

ERROR in ./~/salad-ui.chart/salad-ui.chart.js
Module not found: Error: Can't resolve 'moment' in '.../node_modules/salad-ui.chart'
 @ ./~/salad-ui.chart/salad-ui.chart.js 1:3316-3333
 @ ./components/Dashboard.jsx
 @ ./router/routes.jsx
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server ./index.jsx

Any ideas?

Thanks!

**Comment by samueldelesque** [comment]
Ah my bad - moment is a peer dependency, so you also need to `npm i --save moment`   @flamencoflsh

**Comment by flamencoflsh** [comment]
Hi @samueldelesque !

Thanks for your response... I noticed that when I try to use any of the following:

npm install --save react-simple-charts
npm i --save salad-ui.chart
npm i --save moment

I get this warning: 

npm WARN salad-ui.chart@1.1.46 requires a peer of react-router@^2.4.1 but none was installed.

Do you know what that is about? =)

Thank!

**Comment by samueldelesque** [comment]
It was improperly put in peer dependencies, you can safely ignore the warning.

**Comment by flamencoflsh** [comment]
Thank you, @samueldelesque! I will close this issue, and start a new one for additional questions!

**Comment by flamencoflsh** [comment]
Closed.
