### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by flamencoflsh** [samueldelesque/react-simple-charts#3]
Hi @samueldelesque!  I was wondering about the extent to which the circle chart can be customized.  Where can I find all the attributes that can be changed beside these ones in the sample?

{
    width: 150,
    height: 150,
    border: 'none',
    strokeWidth: 10,
    labelColor: '#111111',
    labelFontSize: '18px',
    strokeColor: '#408AE5',
    railColor: '#f5f5f5',
    fillColor: 'none',
    percent: 70,
    padding: 0,
}

How do you change the circle size/circumference, for example?

Also, is it possible to edit the circle more extensively?  For example to cut part of it, or to display text in the middle?   Here is an example of what I am trying to create: 

<img width="278" alt="screen shot 2017-04-06 at 12 14 09 pm" src="https://cloud.githubusercontent.com/assets/9296896/24764617/c13cfe56-1aa9-11e7-9971-093ca7e280f0.png">

Let me know what you'd suggest or if you have any advice! 

Thanks!

**Comment by flamencoflsh** [comment]
Hi @samueldelesque, I realized that you can set the width of the circle element.  Still curious about the following:

1) The label in the middle of the circle: I noticed that the first character currently always starts at the center of the circle.  How can I go about customizing (e.g. centering, etc.) the text?  

Also, if I would like it to say something other than the percentage number, is there a way to customize?

2) Still curious whether there is a way to 'cut' the circle so that it is not a full circle (as in the image above).

Thanks!

**Comment by flamencoflsh** [comment]
@samueldelesque  One more thing... 

3. Is it possible to start the dial at a different position rather than the top of the circle (the 12 o'clock mark)?  For example, from the bottom of the circle (5 o'clock mark)?

Thanks!

**Comment by samueldelesque** [comment]
Hey @flamencoflsh - would you like to implement those changes 😄  ? 
If so feel free to submit a pull request to https://github.com/samueldelesque/salad-ui

The options you are asking for are not currently implemented.
