### ISSUE TITLE
Percent in circle graph is not centered

### ISSUE THREAD

**Issue by JaLe29** [samueldelesque/react-simple-charts#5]
I am using v 0.0.19.

Percent in circle graph is not centered.

**Actual state**
See image:
![image](https://user-images.githubusercontent.com/22296816/35394911-424f521a-01e9-11e8-8d1f-54163a971460.png)

**Expected state**
Caption is centered in circle graph.

Config:
```
				<CirclePie
					strokeWidth={5}
					railColor={'#d3d3d3'}
					percent={this.state.cpupercentage}
				/>
```

**Comment by samueldelesque** [comment]
Please use the version of this library in https://salad-ui.com
